CREATE TABLE IF NOT EXISTS refresh_tokens(
  id INT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  refresh_token INT NOT NULL,
  expired_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by LONGTEXT NOT NULL,
  updated_by LONGTEXT NOT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_user_id_refresh_tokens FOREIGN KEY (user_id) REFERENCES users(id)
);