CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT NOT NULL,
  email VARCHAR(250) NOT NULL, 
  password VARCHAR(500) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by LONGTEXT NOT NULL,
  updated_by LONGTEXT NOT NULL,

  PRIMARY KEY(id),
  UNIQUE KEY(email)
);